#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

export PATH="/c/Program Files/GitHub CLI:$PATH"
GIT="${GIT:-git}"
command -v git >/dev/null 2>&1 || GIT="/f/Git/cmd/git.exe"
DEPLOY_KEY="${HOME}/.ssh/pulse-github-deploy"
SSH_USER="${SERVER_SSH_USER:-linuxuser}"
TOKEN_FILE="${GH_TOKEN_FILE:-${HOME}/.pulse-gh-token}"

banner "Publish Pulse: GitHub Actions builds the image, the VPS only pulls"

# ── Stage 1: GitHub login ────────────────────────────────────────────────
stage "Log in to GitHub"
say "CI builds the image on GitHub-hosted runners so the 1GB VPS never compiles Pulse."

if [[ -n "${HTTPS_PROXY:-}" ]]; then
  note "Using proxy $HTTPS_PROXY"
else
  note "No HTTPS_PROXY set. If GitHub times out, Ctrl-C and re-run after:"
  note "  export HTTPS_PROXY=http://127.0.0.1:7890  # your local proxy port"
fi

if gh auth status >/dev/null 2>&1; then
  say "gh is already authenticated."
elif [[ -s "$TOKEN_FILE" ]]; then
  say "Signing in with the token in $TOKEN_FILE (no browser needed)."
  tr -d '\r\n' < "$TOKEN_FILE" | gh auth login --hostname github.com \
    --git-protocol https --with-token
else
  warn "No GitHub session and no token file, so sign in by hand once."
  say "A Personal Access Token avoids the browser device flow that timed out."
  open_url "https://github.com/settings/tokens/new?scopes=repo,workflow,write:packages,read:org&description=pulse-monitor"
  step "Generate a classic token with scopes: repo, workflow, write:packages, read:org."
  step "Save it to a file this wizard can read, so it never lands in shell history:"
  note "  printf '%s' 'PASTE_TOKEN_HERE' > \"$TOKEN_FILE\" && chmod 600 \"$TOKEN_FILE\""
  step "Then re-run this wizard; it will pick the token up automatically."
  note "Alternatively run: gh auth login --hostname github.com --git-protocol https --with-token"
  if confirm "Try the browser device flow instead (needs GitHub reachable)?"; then
    gh auth login --hostname github.com --git-protocol https --web --skip-ssh-key \
      --scopes "repo,read:org,workflow,write:packages"
  else
    say "Stopping here. Nothing was changed."
    SKIPPED+=("GitHub sign-in (write the token to $TOKEN_FILE, then re-run)")
    finish
    exit 0
  fi
fi
gh auth status
note "Need repo + workflow + packages so Actions can push to GHCR and deploy."

# ── Stage 2: Commit deploy files ─────────────────────────────────────────
stage "Commit the deploy files"
say "Dockerfile, Compose, Caddy, and the Actions workflow need to be in git before the first push."
"$GIT" status
if "$GIT" diff --quiet && "$GIT" diff --cached --quiet && [[ -z "$("$GIT" ls-files --others --exclude-standard)" ]]; then
  say "Working tree is clean; nothing to commit."
else
  if confirm "Create a commit for the deploy files now?"; then
    "$GIT" add Dockerfile .dockerignore deploy .github/workflows/deploy.yml \
      next.config.ts package.json package-lock.json scripts/build-worker.mjs \
      scripts/publish-pulse-wizard.sh .gitignore
    "$GIT" -c user.name="du changxv" -c user.email="changxvdu@gmail.com" \
      commit -m "feat: publish Pulse with CI-built images and Caddy HTTPS"
  else
    warn "Skipping commit. The next stage cannot push an empty or stale tree."
  fi
fi

# ── Stage 3: Create the public repo (no push yet) ────────────────────────
stage "Create the public GitHub repo"
ask SERVER_IP "VPS IPv4 address:"
write_env SERVER_IP "$SERVER_IP"
write_env SERVER_SSH_USER "$SSH_USER"
if "$GIT" remote get-url origin >/dev/null 2>&1; then
  say "origin already exists: $("$GIT" remote get-url origin)"
else
  step "Creating public repo pulse-monitor from this directory (no push yet)."
  gh repo create pulse-monitor --public --source=. --remote=origin \
    --description "Single-Operator HTTP(S) uptime monitor"
fi
OWNER=$(gh api user -q .login | tr '[:upper:]' '[:lower:]')
IMAGE="ghcr.io/${OWNER}/pulse-monitor:latest"
write_env PULSE_IMAGE "$IMAGE"
write_env PULSE_DOMAIN "${SERVER_IP}.sslip.io"
note "Image will be $IMAGE"
note "Status Page will be https://${SERVER_IP}.sslip.io"

# ── Stage 4: Secrets, then first push ────────────────────────────────────
stage "Store deploy secrets, then push"
if [[ ! -f "$DEPLOY_KEY" ]]; then
  warn "Missing $DEPLOY_KEY — generate one, add the .pub to linuxuser authorized_keys, then re-run."
  SKIPPED+=("DEPLOY_SSH_KEY file $DEPLOY_KEY")
else
  set_secret DEPLOY_HOST "$SERVER_IP"
  set_secret DEPLOY_USER "$SSH_USER"
  set_secret DEPLOY_SSH_KEY "$(cat "$DEPLOY_KEY")"
fi
set_var PULSE_DEPLOY "1"
say "Updating PULSE_IMAGE on the VPS so compose pulls the real GHCR tag."
ssh -i "${HOME}/.ssh/id_ed25519" -o BatchMode=yes -o ConnectTimeout=15 \
  "${SSH_USER}@${SERVER_IP}" "sed -i 's|^PULSE_IMAGE=.*|PULSE_IMAGE=${IMAGE}|' /opt/pulse/.env" \
  || warn "Could not update /opt/pulse/.env; edit PULSE_IMAGE there by hand."
if confirm "Push main to origin now? Actions will test, build, and pull on the VPS."; then
  "$GIT" push -u origin HEAD:main
else
  SKIPPED+=("git push origin main")
fi

# ── Stage 5: Watch the run and open the Status Page ──────────────────────
stage "Watch CI and open the Status Page"
say "The VPS only docker compose pull && up. It does not compile Next.js."
if confirm "Watch the latest GitHub Actions run until it finishes?"; then
  gh run watch --exit-status || warn "The run failed; open the Actions tab."
fi
STATUS_URL="https://${SERVER_IP}.sslip.io"
open_url "$STATUS_URL"
step "Confirm the public Status Page loads over HTTPS (Caddy + Let's Encrypt)."
step "Sign-in stays at ${STATUS_URL}/login ; the console is ${STATUS_URL}/console ."
note "First certificate issue can take a minute. If it fails, check: docker compose logs caddy"
pause "Status Page opened?"

finish
