#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Vultr 服务器开通向导（约 5 美元/月）"

# ── Stage 1: 注册账号 + 付款方式 ─────────────────────────────────────────
stage "注册 Vultr 账号并绑定付款方式"
say "先注册账号并完成付款设置，之后才能部署服务器。"
open_url "https://www.vultr.com/register/"
step "用邮箱注册账号，然后去邮箱点击验证链接。"
step "登录后进入 Billing（账单）页面，绑定付款方式。"
note "支持信用卡 / PayPal / 支付宝（Alipay）。国内用户选支付宝最方便。"
note "留意新用户优惠：Vultr 经常送新账号试用额度（如 \$100 credit）。"
warn "充值最低档即可，实例按小时计费，随时可以销毁止损。"
pause "账号注册并完成付款绑定后，按回车继续"

# ── Stage 2: 本地 SSH 密钥 ───────────────────────────────────────────────
stage "生成（或复用）本地 SSH 密钥"
KEY_PATH="$HOME/.ssh/id_ed25519"
if [[ -f "$KEY_PATH.pub" ]]; then
  say "检测到已有密钥 $KEY_PATH，直接复用。"
else
  say "本机还没有 ed25519 密钥，现在生成一个（提示密码短语时直接回车 = 不设密码）。"
  mkdir -p "$HOME/.ssh"
  ssh-keygen -t ed25519 -f "$KEY_PATH" -C "vultr-deploy"
fi
say ""
say "下面是你的公钥，下一阶段要把它整行粘贴到 Vultr："
printf '\n%s%s%s\n\n' "$GREEN" "$(cat "$KEY_PATH.pub")" "$RESET"
note "公钥不是机密，可以放心粘贴；私钥（无 .pub 后缀的文件）永远不要给任何人。"
pause "已复制上面这行公钥后，按回车继续"

# ── Stage 3: 把公钥添加到 Vultr ──────────────────────────────────────────
stage "在 Vultr 控制台添加 SSH 公钥"
open_url "https://my.vultr.com/settings/#settingssshkeys"
step "在 Account → SSH Keys 页面点击 Add SSH Key。"
step "Name 填 vultr-deploy（或任意名字），Key 粘贴上一步复制的整行公钥。"
step "点击 Add SSH Key 保存。"
note "如果页面没自动打开，登录 my.vultr.com 后走 Account → SSH Keys。"
pause "公钥添加成功后，按回车继续"

# ── Stage 4: 部署实例 ────────────────────────────────────────────────────
stage "部署 \$5/月 实例"
open_url "https://my.vultr.com/deploy/"
step "类型选 Cloud Compute（Shared CPU），CPU/存储技术选 Regular Performance。"
step "机房位置：推荐 Tokyo / Osaka / Singapore（国内访问延迟较低），也可按目标用户选。"
step "操作系统选 Ubuntu 24.04 LTS x64。"
step "套餐选 25 GB SSD · 1 vCPU · 1 GB 内存 · 1 TB 流量，标价 \$5.00/mo（规格代号 vc2-1c-1gb）。"
step "Auto Backups（自动备份）建议关掉：它每月多收约 \$1，我们会用 Litestream 自己做备份。"
step "SSH Keys 一栏勾选刚才添加的 vultr-deploy 公钥（这步很重要，别漏）。"
step "Server Hostname 随意，比如 pulse-monitor。确认月费后点 Deploy Now。"
note "部署后等 1-2 分钟，实例状态变成 Running，点进实例详情页能看到 IP Address。"
ask SERVER_IP "实例的 IPv4 地址是（形如 45.76.x.x）:"
write_env SERVER_IP "$SERVER_IP"
write_env SERVER_SSH_USER "root"
note "IP 已存入 .env（已被 gitignore，不会提交）。后续部署脚本会读取它。"

# ── Stage 5: 验证 SSH 连通 ───────────────────────────────────────────────
stage "验证 SSH 连接"
say "尝试用密钥连接 root@$SERVER_IP ..."
if ssh -i "$KEY_PATH" -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 \
     "root@$SERVER_IP" 'echo __connected__' 2>/dev/null | grep -q '__connected__'; then
  say "${GREEN}✓ SSH 连接成功，服务器已就绪！${RESET}"
  note "接下来可以让 agent 远程完成系统加固和 Docker 安装。"
else
  warn "连接失败。常见原因："
  note "  - 实例还在初始化：等 1-2 分钟再重跑本向导（已保存的值会记住）"
  note "  - 部署时忘了勾选 SSH Key：去实例详情页确认，必要时销毁重建（按小时计费，损失几乎为零）"
  note "  - 本地网络对 22 端口的出站限制：换个网络试试"
fi

finish
